services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: amlak
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    command: sh -c "npx prisma generate && npx prisma db push && npx tsx watch src/app.ts"
    environment:
      - PORT=4000
      - DATABASE_URL=postgresql://postgres:1234@db:5432/amlak
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app                # اتصال مستقیم کدهای لوکال به کانتینر
      - /app/node_modules  
    depends_on:
      - db
